### ISSUE TITLE
Batched classes todo list

### ISSUE THREAD

**Issue by pratikvn** [ginkgo-project/ginkgo#1376]
This issue tracks the different aspects of the batched functionality that reviewers have suggested, but still need to be implemented:

### `batch::MultiVector`
1. Performance related:
+ [ ] Handling multiple RHS, or special case for single rhs 
+ [ ] Workgroup sizes for DPCPP

2. Utility related:
+ [ ] Add stride capability.

3. Code simplifications:
+ [ ] Using a common launcher syntax, something similar to `parfor_batch_blockwise(x, [](ibatch) { ... })`
