### ISSUE TITLE
Release 1.9.0 Checklist

### ISSUE THREAD

**Issue by MarcelKoch** [ginkgo-project/ginkgo#1738]
# Pre Release / Prerequisites

- [ ] Create release project and milestone
- [ ] Manage open bugs
- [ ] Check CUDA/HIP/SYCL versions
  - [ ] Remove code for unsupported versions

# Step-by-Step

- [ ] Create release branch `release/X.Y.Z` from `develop`
- [ ] Change version tag in `CMakeLists.txt` to `main`
- [ ] Update TPLs
- [ ] Run threadsanitizer CI locally (until enabled again)
- [ ] Write release notes
- [ ] Merge release branch into main (with `--no--ff`)
- [ ] Until 2026:
  - [ ] Create branch `master-release/X.Y.Z` from `main`
  - [ ] Change version tag to `master`
  - [ ] Merge into `master` (this will introduce ~6000 commits into `master` when done for the first time, it should be significantly less for following releases)
- [ ] Create github release with new tag `vX.Y.Z` on `main`

# Post Release

- [ ] Announce the release:
  - [ ] LinkedIn
  - [ ] E-Mail lists: NADigest
- [ ] Add new version to package managers
  - [ ] spack: https://github.com/ginkgo-project/spack
  - [ ] vcpkg
- [ ] Update version on develop to `X.Y+1.0`

**Comment by MarcelKoch** [comment]
This issue is also meant to become a new template which we will use for following releases.

**Comment by MarcelKoch** [comment]
This release approach contains some changes to the previous releases, especially how `master` is handled. 

I think in earlier releases all commits after the last release where cherry-picked onto master with an additional merge commit. Although I'm not entirely sure about that. The point is however that the `develop` branch was **not** merged into `master`.

I think this should change, and the release PR should just be a normal merge from `develop` into `master`. This is not really possible, since `master` and `develop` don't have a common history (or at least after the 1.0 release). Thus I'm introducing the `main` branch which will have the future releases. This branch will have a shared history with `develop` in the form of the release merge commits. Here is a diagram how I think the `main`, and `develop` branch should be connected (`feature` stands for our normal development workflow, but that can be realized without a bunch of extra branches):
```mermaid
gitGraph TB:
	commit
	branch develop
	checkout develop
	commit
	branch feature
	checkout feature
	commit
	commit
	checkout develop
	merge feature
	checkout feature
	commit
	commit
	checkout develop
	merge feature
	checkout main
	merge develop tag: "vX.Y.Z"
	checkout feature
	commit
	commit
	checkout develop
	merge feature
	checkout feature
	commit
	commit
	checkout develop
	merge feature
	checkout main
	merge develop tag: "vX'.Y'.Z'"
```

**Comment by upsj** [comment]
We should also add Conan to the package managers, even though we don't really do much work there.

On the release workflow, I want to propose a slight change:

If we introduce the "Change version tag in CMakeLists.txt to main" change into `develop` as well, we can separate this into a PR (PR1) on `develop` that changes the tag (few lines) and a PR (PR2) on `main` that is purely fast-forwarding `main` onto `develop`, and then a PR (PR3) that reverts the first PR on `develop`. That means that PR1 and PR3 are easy to review, and PR2 doesn't include any new changes, so it doesn't need any actual reviews.

**Comment by MarcelKoch** [comment]
I guess the question is if we want to have an extra merge commit on main to denote the release. I think we can use your approach either way, and I would also prefer it.

**Comment by yhmtsai** [comment]
are the vcpkg and conan contributed by us?
the update version in post release should be `X.Y.Z` -> `X.(Y+1).0` for minor update

**Comment by yhmtsai** [comment]
For merging to master, I assume you will not change the version tag as master from the beginning.
should we just squash all commit to the master?

**Comment by MarcelKoch** [comment]
For master, I initially thought I would just cherry pick all commits from develop into master. But squashing all the commits might be the better choice. I don't really care how the history of master will look like in the future, I just want to have the latest changes in it. 
I will also leave the tags as they already are.

**Comment by MarcelKoch** [comment]
BTW you can see how the history of the main branch should look like at: https://github.com/MarcelKoch/ginkgo/tree/main-with-merges. This example has two merges from develop into the main branch to "simulate" our release process.
@upsj I would actually prefer to have explicit merge commits instead of fast-forwarding. I don't think you can FF merge through the github PR interface anyway. The explicit merge commits also have the effect that using the `--first-parent` option when looking at the history, will directly give you the release commits.

**Comment by yhmtsai** [comment]
It will also be great if you can link the step to the pr such that we might be able to see more detail on that.
Some of them sometimes are not obvious like link name from develop to main in ReadME.md
