### ISSUE TITLE
Current NOT_IMPLEMENTED kernels

### ISSUE THREAD

**Issue by thoasm** [ginkgo-project/ginkgo#286]
We should discuss what kernels we should implement before the release. Since I lost the overview, I looked in the code and searched for kernels which are marked as `GKO_NOT_IMPLEMENTED`.

Interestingly, we do not support `Coo::transpose` and `Coo::conj_transpose` anywhere, which should be fairly trivial to implement (swapping `col_idxs_` and `row_idxs_` with `std::move`, followed by complex conjugation for `conj_transpose`).

The big question is: what should we implement before the first release?

The following are lists of `GKO_NOT_IMPLEMENTED` kernels (which are actually not implemented and not just have a case which is not implemented):
### CUDA
- Coo
  - [ ] `transpose`
  - [ ] `conj_transpose`
- Csr
  - [ ] `move_to_dense` _(can be replaced with `convert_to_dense`)_
- Dense
  - [ ] `move_to_csr` _(can be replaced with `convert_to_csr`)_
  - [ ] `move_to_ell` _(can be replaced with `convert_to_ell`)_
  - [ ] `convert_to_hybrid`
  - [ ] `move_to_hybrid` _(can be replaced with `convert_to_hybrid`)_
  - [ ] `move_to_sellp`  _(can be replaced with `convert_to_sellp`)_
- Hybrid
  - [ ] `convert_to_dense`

__NOTE:__ All `move_to_XXX` kernels in `Dense` can easily be removed, and the functionality replaced by `convert_to_XXX` (which we should definitively do).
### Reference
- Coo
  - [ ] `transpose`
  - [ ] `conj_transpose`

### OMP
- Coo
  - [ ] `transpose`
  - [ ] `conj_transpose`
- Csr
  - [ ] `convert_to_ell` __after__ #250
  - [ ] `calculate_max_nnz_per_row` __after__ #250
  - [ ] `convert_to_sellp` __after__ #279
  - [ ] `calculate_total_cols` __after__ #279
- Ell
  - [ ] `convert_to_csr` __after__ #250
  - [ ] `count_nonzeros` __after__ #250
- Sellp
  - [ ] `convert_to_csr` __after__ #279
  - [ ] `count_nonzeros` __after__ #279
- Gmres
  - [ ] All Kernels (@fritzgoebel is working on this)

## Current conversions supported (maybe not fully implemented)

- __Coo__
  -> Csr
  -> Dense
- __Csr__
  -> Coo
  -> Dense
  -> Ell __after__ #250
  -> Sellp  __after__ #279
- __Dense__
  -> Coo
  -> Csr
  -> Ell
  -> Hybrid
  -> Sellp
- __Ell__
  -> Csr __after__ #250
  -> Dense
- __Hybrid__
  -> Dense
- __Sellp__
  -> Csr   __after__ #279
  -> Dense

__NOTE:__ If we want to support all conversions from and to Csr and Dense, we are missing: __Csr <-> Hybrid__

**Comment by thoasm** [comment]
I will definitively take care of the `move_to_XXX` replacements, but for the others, we should discuss what is necessary.
I can also take care of the `COO::transpose`, it should also be pretty straight forward.

**Comment by hartwiganzt** [comment]
I think the reference transpose and conjugate transpose should be easy. No need for the other executors.
I don't have a strong opinion on the others - I think they are all optional.

**Comment by thoasm** [comment]
`transpose` in general is easy, I don't even have to implement any kernels (since I just swap the col and row index arrays).
Additionally, I think we should also implement at least the __OMP__ kernels, so we actually support everything with OMP that we do with CUDA.

**Comment by tcojean** [comment]
I tried to check everything that is "taken care of". Overall, what is left I think is:
+ CUDA Dense <-> Hybrid conversions (hard to implement AFAIK)
+ OpenMP CSR <-> Ell, Sellp
+ Everywhere CSR <-> Hybrid

I believe none are that much required for the release.

**Comment by thoasm** [comment]
That is true, I removed the dependency to the Release. We also said previously that we do not require the OpenMP kernels since we have the reference version.
