### ISSUE TITLE
Featue requests

### ISSUE THREAD

**Issue by thoasm** [ginkgo-project/ginkgo#639]
This issue is supposed to centralize all feature requests and list what features are currently worked upon.

__If you have a request, please comment below with the use-case you have for it.__

Currently, we are working on:
- [ ] Reverse Cuthill-McKee (#500)
- [ ] AMG (#528)
- [ ] Induced Dimension Reduction (IDR) (#620)
- [ ] Compressed Basis GMRES (where krylov bases are stored in lower precision)
- [ ] Computation of absolutes of matrices (#636)
